version: '3'
services:
    nginx:
        image: nginx:latest
        restart: always     
        ports: 
            - "9080:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./public:/opt/www
            - ./logs:/opt/logs
        links:
            - nodejs
    nodejs:
        build: ./image
        restart: always
        ports: 
            - "9080:8000"
        volumes:
            - ./app:/opt/app